### ISSUE TITLE
パラメーターについて

### ISSUE THREAD

**Issue by nesosuke** [nesosuke/Yondero#9]
/attatchments/{article_id} ってもしかして {attathchment_id}の方が良くないか？
結びつける動作は別で書いたほうが良い気がする．

![image](https://user-images.githubusercontent.com/16930989/165007858-d297431c-b2c7-458d-8c31-01169c6d36ed.png)

_Originally posted by @nesosuke in https://github.com/nesosuke/Yondero/issues/8#issuecomment-1107980548_

**Comment by cormojs** [comment]
DBに保存される概念の関係上 attachment が article に属しているのだとすると

`/attachments/{article_id}` よりは `/articles/{article_id}/attachments` とする方がRESTっぽいかなと思います。

また、ある article に属する attachment のうち一つだけに操作をしたい場合は `/articles/{article_id}/attachments/{attachment_id}` とするパターンもありそうです。

あるいはDB上 attachment と article の関係がない(または後付けでしかない)場合は `/attachments/{attachment_id}` としてもよさそうです(article との関係をクエリパラメータで表してもよい)。

**Comment by nesosuke** [comment]
articleとattatchmentの関係については，

> attachment と article の関係がない(または後付けでしかない) 

の「後付け」のつもりで考えていて，DBでの処理として`articles`に`attachment_id`を追記，あるいはarticle_idとattachment_idを紐付けるテーブルを作成する方法で良いかなと考えています．
なので，`/attatchments/{attatchment_id}` を考えていました．
（補足：Mendeley Desktopで文献情報を入力しなくともPDFをD&Dでインポートできることから，密でなくてもいいかと考えていました．）

ただ，

> `/attachments/{article_id}` よりは `/articles/{article_id}/attachments` とする方がRESTっぽい

勉強になります．
この方法は`/attatchments/{attatchment_id}`より良いと感じていて，こうしておくと先にファイルがアップロードされた場合でもarticle_idはすでに生えているので，後々の実装が楽なような気がしました．候補に考えておきます．

> ある article に属する attachment のうち一つだけ

これについては，先述と矛盾する気がしますが，articleとattatchmentの対応数 は精々 1:1 対応を想定しています（文献情報と文献本体の関係）．
重複の対処についてはまだ考えていませんが， 409 "Conflict" と[DELETE] `/articles/{article_id}`（または`/attatchments/{attatchment_id}`）があるので，対応は後でもいいかなと考えています．
そういうわけで， `/articles/{article_id}/attachments/{attachment_id}` というネストは考えていませんでした．


要するに，2番目の案が腑に落ちています．Thx.

**Comment by nesosuke** [comment]
とりあえずこんな感じで書き換えてみたんですけど，( 
https://mstdn.home.neso.tech/@neso/108191762416889395 ) のようなファイルが先に投げられる使い方を想定しているのもあって，主従が実は逆なんじゃないかと思い始めてきた（文献本体が主，文献情報は従）

![image](https://user-images.githubusercontent.com/16930989/165051773-d8df8ae5-e201-4cb3-8e29-76710e3d9aaf.png)

**Comment by nesosuke** [comment]
#11 妥協点．
![image](https://user-images.githubusercontent.com/16930989/165144012-86c04d36-2240-479b-a73b-3f132a55d4cc.png)
